### ISSUE TITLE
Negative health

### ISSUE THREAD

**Issue by cashenkes** [derpfacedirk/Goldiriath#16]
On the scoreboard the health meter is able to go negative. If the health meter reaches a value of -100 it crashes.

**Comment by JeromSar** [comment]
Related log entry:

```
23.08 11:36:51 [Server] WARN Task #8224 for Goldiriath v0.0.1 generated an exception
23.08 11:36:51 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.1-SNAPSHOT.jar:git-Spigot-1627]
23.08 11:36:51 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10-R0.1-SNAPSHOT.jar:git-Spigot-1627]
23.08 11:36:51 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10-R0.1-SNAPSHOT.jar:git-Spigot-1627]
23.08 11:36:51 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10-R0.1-SNAPSHOT.jar:git-Spigot-1627]
23.08 11:36:51 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot-1.7.10-R0.1-SNAPSHOT.jar:git-Spigot-1627]
23.08 11:36:51 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.7.10-R0.1-SNAPSHOT.jar:git-Spigot-1627]
23.08 11:36:51 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.7.10-R0.1-SNAPSHOT.jar:git-Spigot-1627]
23.08 11:36:51 [Server] INFO at me.dirkjan.goldiriath.HeartBeat.run(HeartBeat.java:21) ~[?:?]
23.08 11:36:51 [Server] INFO at me.dirkjan.goldiriath.player.PlayerManager.updateAll(PlayerManager.java:106) ~[?:?]
23.08 11:36:51 [Server] INFO at me.dirkjan.goldiriath.player.GPlayer.update(GPlayer.java:86) ~[?:?]
23.08 11:36:51 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scoreboard.CraftObjective.getScore(CraftObjective.java:98) ~[spigot-1.7.10-R0.1-SNAPSHOT.jar:git-Spigot-1627]
23.08 11:36:51 [Server] INFO java.lang.IllegalArgumentException: Entry cannot be longer than 16 characters!
```

**Comment by JeromSar** [comment]
https://github.com/Goldiriath/Goldiriath/commit/07aff694250d313aca9332e300295dea124a882f partially fixes this.

**Comment by JeromSar** [comment]
Pending fix: https://github.com/Goldiriath/Goldiriath/pull/68
