### ISSUE TITLE
Giving items to players through scripts not working

### ISSUE THREAD

**Issue by derpfacedirk** [derpfacedirk/Goldiriath#66]
trying to give an item to a player in a quest file gives the following error message: 
```[15:35:35] [Server thread/WARN]: [Goldiriath] [response_bow] Skipping script line: 0 item add _stick_and_string. 3```
the item is in the item config

**Comment by JeromSar** [comment]
@derpfacedirk Could you provide the error/exception shown in config when this happens. Additionally, please provide the exact script item used to cause this issue.

**Comment by derpfacedirk** [comment]
script item:
``` 
stick_and_string:
    name: 'Stick And Sting'
    type: BOW
    data: 0
    level: 1
    tier: BATTERED
```
full error: 
```
[23:22:42] [Server thread/WARN]: [Goldiriath] [response_bow] Skipping script line: 0 item add _stick_and_string. 3
[23:22:42] [Server thread/ERROR]: [Goldiriath] net.goldiriath.plugin.game.questing.script.ParseException: 3
	at net.goldiriath.plugin.game.questing.script.ScriptParser.parse(ScriptParser.java:127)
	at net.goldiriath.plugin.game.questing.dialog.Dialog.loadFrom(Dialog.java:41)
	at net.goldiriath.plugin.game.questing.dialog.NPCDialogHandler.loadFrom(NPCDialogHandler.java:103)
	at net.goldiriath.plugin.game.questing.dialog.DialogManager.onStart(DialogManager.java:71)
	at net.goldiriath.plugin.util.service.AbstractService.start(AbstractService.java:50)
	at net.goldiriath.plugin.ServiceManager.onStart(ServiceManager.java:33)
	at net.goldiriath.plugin.util.service.AbstractService.start(AbstractService.java:50)
	at net.goldiriath.plugin.Goldiriath.enable(Goldiriath.java:129)
	at net.pravian.aero.plugin.AeroPlugin.onEnable(AeroPlugin.java:75)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389)
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:352)
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:326)
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:282)
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at net.goldiriath.plugin.game.questing.script.item.ItemScript.<init>(ItemScript.java:28)
	at net.goldiriath.plugin.game.questing.script.ScriptParser.parse(ScriptParser.java:74)
	... 19 more
```

**Comment by JeromSar** [comment]
The usage of your script line is wrong. You are missing the `<amount>` specifier.
